set(_CATKIN_CURRENT_PACKAGE "lophorina")
set(lophorina_VERSION "0.0.0")
set(lophorina_MAINTAINER "luis <luis@todo.todo>")
set(lophorina_PACKAGE_FORMAT "2")
set(lophorina_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "gazebo_ros")
set(lophorina_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "gazebo_ros")
set(lophorina_BUILDTOOL_DEPENDS "catkin")
set(lophorina_BUILDTOOL_EXPORT_DEPENDS )
set(lophorina_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(lophorina_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "gazebo_ros")
set(lophorina_TEST_DEPENDS )
set(lophorina_DOC_DEPENDS )
set(lophorina_URL_WEBSITE "")
set(lophorina_URL_BUGTRACKER "")
set(lophorina_URL_REPOSITORY "")
set(lophorina_DEPRECATED "")