pid_gains:
    base_link_to_motor_front_right:
      p: 100.0 
      i: 0.01
      d: 10.0
    base_link_to_motor_front_left:
      p: 100.0 
      i: 0.01
      d: 10.0
    base_link_to_motor_back_right:
      p: 100.0 
      i: 0.01
      d: 10.0
    base_link_to_motor_back_left:
      p: 100.0 
      i: 0.01
      d: 10.0
    motor_front_right_to_front_right_propeller:
      p: 100.0 
      i: 0.01
      d: 10.0
    motor_front_left_to_front_left_propeller:
      p: 100.0 
      i: 0.01
      d: 10.0
    motor_back_right_to_back_right_propeller:
      p: 100.0 
      i: 0.01
      d: 10.0
    motor_back_left_to_back_left_propeller:
      p: 100.0 
      i: 0.01
      d: 10.0

