lophorina:
  # Publish all joint states -----------------------------------
  lophorina_joint_state_controller:
    # The joint state controller handles publishing transforms for any moving joints
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  # Position Controllers ---------------------------------------  
  lophorina_prop_controller:
    type: "velocity_controllers/JointGroupVelocityController"
    joints:
      - motor_front_right_to_front_right_propeller
      - motor_front_left_to_front_left_propeller
      - motor_back_right_to_back_right_propeller
      - motor_back_left_to_back_left_propeller

  lophorina_tilt_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
    - base_link_to_motor_front_right
    - base_link_to_motor_front_left
    - base_link_to_motor_back_right
    - base_link_to_motor_back_left

  gazebo_ros_control:
    pid_gains:
      base_link_to_motor_front_right:
        p: 1
        i: 0
        d: 0
      base_link_to_motor_front_left:
        p: 1
        i: 0
        d: 0
      base_link_to_motor_back_right:
        p: 1
        i: 0
        d: 0
      base_link_to_motor_back_left:
        p: 1
        i: 0
        d: 0
      motor_front_right_to_front_right_propeller:
        p: 1
        i: 0
        d: 0
      motor_front_left_to_front_left_propeller:
        p: 1
        i: 0
        d: 0
      motor_back_right_to_back_right_propeller:
        p: 1
        i: 0
        d: 0
      motor_back_left_to_back_left_propeller:
        p: 1
        i: 0
        d: 0