type: "position_controllers/JointGroupPositionController"
joints:
  - base_link_to_motor_front_right
  - base_link_to_motor_front_left
  - base_link_to_motor_back_right
  - base_link_to_motor_back_left

